language: node_js
node_js:
- '9'
- '8'
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run test
- npm run build:prod
after_success:
- npm run report-coverage
deploy:
  provider: heroku
  node: '9'
  api_key:
    secure: dNzABLOUL+pylNLTFWIKaDEgtdrFfCs0qj14PWg/7Niu3abImEapA5HnO44NKeTkgJ/XVKME47junFf2ID76fJz0qme8KBK1b0U1UISDiUrYChUQJH3HMLtRQ4qn/T5J4oOg2d18nhub8lgbRNj8a6HX3m1gdvho8I36arsES3yW+NZquUue8W2ZxrmZ2F+cUqZsguH5uYBcWFbdUSJdD1mRo6vstr38gGRbx/Rj1e4n+SHTy+EfGNlrccFO9y3/b1t7oDj06mAHdmRMyVz/JufT8kY/6cNJ1KZM15qdHXRFhTQxUk2AFGF34VvjgbrDhDWEmRC2xk7zx4Djvd9xO8ys6PfEa8eDPqAkp2oZRI/mlEjUUKbwE4kxP3tDocBbwfsIGsAruBqqOii1J4iIgrKLJYPYQNauMNKQvE2LYgbptuAOg9oG/RzMMiRrLxLulYqXY+U3VQy9gCrvmVIUp4jFmnT2mT01oBXwDSBFoFZSyc8SJ3VX/J72iLrIWrxrFT1kgIOxPLlHIZGOxarLfMaUzA7Yr2bEiwEohvHkYY8+j5LrLLLrNntXFslfGcuSKNTKCRuokHrdGh0DOi16FvnNkDok/zFZ0K0dw6nvtmDNdTfR0t0FwBz5Q7ybicRmXt8P+X42ph+cQPOY2AiDOQ6OkZoTDojdHQT6KQqsWKY=
  skip_cleanup: true
