language: node_js
node_js:
- '10'
- '9'
- '8'
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run demo:test
- npm run demo:build:prod
after_success:
- npm run report-coverage
deploy:
  provider: heroku
  app: webpack-scaffold
  api_key:
    secure: EmUH0tVBZBlcheT6GU2FLaWD4ltNKCVoXz3m//EvKcbK4Vw9edQZgQfyb4Fzkr3DqTEF/9VGj7SMfiX3OfDgA7DHDylOXfETlw+W2/nqEgEp6bV6SDKIbMcHpioGjXZi557gf18uX66XK7KSjIHofamUyC3mhVT4WGVu56bMalqxbnzMPGrX1k8sIa6UK3xyf6dz0kGrHeZ80TRP3RnpexL6U9jmjZEgtED99RcApQFdPRGyrHruiOI7kGE63w395tcZB9OCWB+FTf4Xe/i4o7Kormu1wZZ41bloSl727WlfC9GOqNjvTm0KrBxZKVNJ89T87JXqi7tBM4Ly/hfftpuYrnLFrdimDvuk92xg4EFqfs9UeEGX991UVQ3pLsgC6+K/f+S7FzJ2FASb3/Dkw5x1OX4pJxeutpFb5vSnPDE5wP78S4CAlSjkZXs28YVaN4UA/su9+O/voUusYJX/jEjPJ0nEqA08Y3yLo06hRF4vpVtfg1Kg2cowCYC6SjZkTp9oe2m2YGEGRfheSkmuzYx26s9rYx5Jv9OCwnCTFjGBXSdzdT4hMgJetaTeTe9AHjX3yzaTbq28XHKb+KsiBp9jFy6cmxcRws7bZGbDyQQMvbVX8F9UcPDIPDInJrw0KYo1s3Tf4F+KQWN/giR+kwEakBZR/59UgLc3Hr/VL8E=
  skip_cleanup: true
  on:
    branch: master
    node_js: '10'
