language: node_js
node_js:
- '10'
- '9'
- '8'
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run demo:test
- npm run demo:build:prod
after_success:
- npm run report-coverage
deploy:
  provider: heroku
  app: webpack-scaffold
  api_key:
    secure: tRE7cOSixms6SgFuNeJCJlBMkouyy1lT67RdUrJMMSP0fVbf0s/ycX/VGAXyUcNnhi8ETZ1zIFA8SxAL4qj4peO2gYNNOVAKOIOa1HleBBknSin8EuNZi2PyCaN/jl7GNrfdp0t3GufLXL8wO2voSvUnpnPbiQ3NiviAwcC+adp0RtD8O1gB3OzHa82rYTLepq1QDQAMW6YocTL9Tp2ZB5qpFDBCzvhQzq/iFTlyhPXGMeay7tN/+Ok9fvp/m2drVa98HDF9x7KEzTvU+DWq9gkKOzcatow0LCHndW5+PSAIIVAqYG/2upOXDhJ3u/9hBLf+Y2yJIPq3R5hML8IMr6CYHcpALxQ/0LiBXlJ/Ava2rP6eT1nfiNfCyBpeNGR1/w/zGDB5A1AhOZVB561o8tcegsbNK5sZOrEhSyvQw30Y4Td8vpUsmaL6eKVO/Duu3riQJttohDXtQ0xhIY27IygvDJQo6IVkmrx98nGGuGJksEA+riurbO2eI30/pNVA7Cwx/pWphZQLcWiL4Y4inyVvdsLEEZmg/q0iiVpwFZd7khK15sNGuOzoRUttwqglT07HdubQ5DuTfFvxNgGqzdBUb7h84Dznc+6JnO4QaKe7JwBD5Vj5SHnoL4CEH0iWXMT9v3bc+E5M7oMBPk58gJmqtrnpDdtWRoEEvEGC4vE=
  skip_cleanup: true
  on:
    branch: master
    node_js: '10'
