# Test against the latest version of this Node.js version
environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "9"
    - nodejs_version: "8"

platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Update build version
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version.build.$env:APPVEYOR_BUILD_NUMBER"
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm -g install npm@6
  # install modules
  - npm i

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run demo:test

build_script:
  # run production build
  - npm run demo:build:prod

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"

# Don't actually build.
build: off
